config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'
  get 'itinerary' => 'pages#itinerary'
  get 'faq' => 'pages#faq'
  get 'reminders' => 'pages#reminders'
  get 'contact' => 'pages#contact'
  get 'register' => 'pages#contact'
  post 'do_register' => 'pages#do_register'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :participants, inverse_of: :member
  accepts_nested_attributes_for :participants, allow_destroy: true

  validates_presence_of :email, :last_name, :first_name, :member_number, :contact_number, :payment_option
  validates :i_agree, acceptance: { accept: true }

  after_create :email_notifications

private
  def email_notifications
    RegistrationMailer.success(email).deliver_later
    AdminMailer.registration(self.id).deliver_later
    return true
  end
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :member
  validates_presence_of :member
  validates_presence_of :email, :last_name, :first_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
    @member = Member.new
    @member.participants.build
  end

  def faq
  end

  def itinerary
  end

  def reminders
  end

  def do_register
    @member = Member.new(member_params)

    if @member.save
      render action: :thank_you
    else
      render action: :contact
    end
  end

  private
  def member_params
    parameters = [:last_name, :first_name, :member_number, :email, :contact_number, :payment_option, :i_agree]
    parameters << { participants_attributes: [:first_name, :last_name, :nickname, :birthdate, :email, :medical_condition, :hobbies, :shirt_size, :diet] }
    params.require(:member).permit(parameters)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>My EO Next Gen 2016</title>

        <meta charset="utf-8">

        <!-- Always force latest IE rendering engine or request Chrome Frame -->
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic' rel='stylesheet' type='text/css'>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body class="<%= controller.action_name %>">
        <%= yield %>
    </body>
</html>

app/views/pages/contact.erb
<%= render partial: "shared/nav" %>
<div class="contact__container">
  <h1 class="registration__header">Register</h1>

  <div class="block__container">
    <div class="block one-half">
      <%= render partial: "shared/reg/member_form", locals: { member: @member } %>
      <% render partial: "shared/reg/payment" %>
      <% render partial: "shared/reg/thankyou" %>
      <% render partial: "shared/reg/kidReg" %>
    </div>

    <div class="block one-half">
      <%= image_tag "register-image.jpg", class: "register__image" %>
    </div>
  </div>

</div>

app/views/pages/faq.erb
<%= render partial: "shared/nav" %>
<div class="faq__container">

  <div class="block__container">

    <div class="block one-third faq__block-first">
      <div class="faq__inner-block">
        <div class="faq__image"><%= image_tag 'faq/faq-header.jpg' %></div>
        <p>Frequently Asked Questions</p>
        <div class="faq__image"><%= image_tag 'faq/faq-hand.jpg' %></div>
      </div>
    </div>

    <ul class="block two-thirds faq__block-list">

      <li class="faq__block-list-item">
        <div class="faq__inner-block">
          <p>Who What When Where</p>
          <button data-target="workshopModal" class="faq__button">+</button>
        </div>
        <%= render partial: "shared/faq/wwww" %>
      </li>

      <li class="faq__block-list-item">
        <div class="faq__inner-block">
          <p>What's Going to Happen?</p>
          <button data-target="miscModal" class="faq__button">+</button>
        </div>
        <%= render partial: "shared/faq/happen" %>
      </li>

      <li class="faq__block-list-item">
        <div class="faq__inner-block">
          <p>Attendees</p>
          <button data-target="attendeesModal" class="faq__button">+</button>
        </div>
        <%= render partial: "shared/faq/attendees" %>
      </li>

      <li class="faq__block-list-item">
        <div class="faq__inner-block">
          <p>Transportation and Accomodation</p>
          <button data-target="transportModal" class="faq__button">+</button>
        </div>
        <%= render partial: "shared/faq/transport" %>
      </li>

      <li class="faq__block-list-item">
        <div class="faq__inner-block">
          <p>Safety and Security</p>
          <button data-target="safetyModal" class="faq__button">+</button>
        </div>
        <%= render partial: "shared/faq/safety" %>
      </li>

      <li class="faq__block-list-item">
        <div class="faq__inner-block">
          <p>Drop Off and Pick Up</p>
          <button data-target="dropOffModal" class="faq__button">+</button>
        </div>
        <%= render partial: "shared/faq/drop_off" %>
      </li>

    </ul>

</div>

app/views/pages/index.erb
<%= render partial: "shared/nav" %>
<div class="landing-page__container block__container">
  <div class="block one-half landing-page__left">
    <%= image_tag "landing-bizwars.png", title: "MY EO Next Gen Manila", class: "landing-page__logo" %>
    <div class="landing-page__copy">
      <p>Give your teens an eye-opening, mind-blowing camp experience this spring break!</p>
      <a href="#learnmore" class="learn-more"><span>Learn More</span></a>
    </div>
  </div>
</div>
<hr class="landing__divider"/>
<div id="learnmore" class="landing-page__container block__container">
  <div class="block two-thirds">
    <div class="landing__about-info">
      <h1>What is My EO Next Gen Manila?</h1>
      <p>MyEO NextGen Manila is a 4-day entrepreneurs camp for teenagers where the next generation entrepreneurs will get the opportunity to:</p>
      <ul>
        <li>learn and hone exciting new skills on collaboration, innovation, and personal leadership</li>
        <li>rethink and reinvent ways of developing innovative products</li>
        <li>nurture the entrepreneurial spirit</li>
        <li>make new friends from all over the globe</li>
      </ul>
      <p>This year’s Biz Wars theme will see teams of campers competing against each other as they learn and put into practice the skills needed to run a successful pop-up business!</p>
    </div>

    <div class="landing__about-info">
      <%= image_tag "about-info/attendees.jpg" %>
      <div class="landing__about-info--copy">
        <h2>Who is this for?</h2>
        <p>Teenagers aged 13-19 years old who are children of EO, YPO, and EO Accelerator members and their relatives.</p>
      </div>
    </div>

    <div class="landing__about-info">
      <%= image_tag "about-info/location.jpg" %>
      <div class="landing__about-info--copy">
        <h2>When and Where</h2>
        <p><em>31 March to 3 April, 2016</em><br>New World Hotel Makati</p>
      </div>
    </div>

    <div class="landing__about-info">
      <%= image_tag "about-info/fees.jpg" %>
      <div class="landing__about-info--copy">
        <h2>Fees and Payments</h2>
        <p>U$D 1,500 per participant</p>
      </div>
    </div>

    <div class="landing__about-info">
      <%= image_tag "about-info/sign-up.jpg" %>
      <div class="landing__about-info--copy">
        <h2>For inquiries...</h2>
        <p>Contact <a href="mailto:inquiries@myeonextgen.com">inquiries@myeonextgen.com</a></p>
      </div>
      <br />
      <br />
      <br />
      <a href="itinerary.html" class="learn-more"><span>View Itinerary</span></a>
    </div>

  </div>
</div>

app/views/pages/itinerary.erb
<%= render partial: "shared/nav" %>
<div class="itinerary__container">
  <h1 class="itinerary__header">Itinerary</h1>
  <p>Here’s a sneak peek of what to expect!</p>

  <div class="block__container">

      <div class="itinerary__row">
        <div class="itinerary__inner-row">
          <div class="block one-third">
            <h1>Day 1</h1>
            <h2>Setting the Stage</h2>
            <p>What is this BootCamp all about?  On our first day, we meet our fellow campers, discover new things about ourselves, and get introduced to the challenge that awaits us.</p>
            <p>Being able to manage a business takes skilful planning and knowing who and what talents are available to us.</p>
          </div>
          <div class="block two-thirds"><%= image_tag 'itinerary/day-1-2016.jpg' %></div>
        </div>
      </div>

    <div class="itinerary__row">
        <div class="itinerary__inner-row">
          <div class="block one-third">
            <h1>Day 2</h1>
            <h2>What's Cooking?</h2>
            <p>We begin with a special tour of establishments in the area, exploring and learning from the professionals to gain inspiration from their success and how their ability to overcome their obstacles.</p>

            <p>We take on essential tools, techniques through interactive modules and guest speakers that will help build our confidence in running our businesses.  Ending the day, we laugh as we learn how to create a positive way to grow ideas and solve problems.</p>
          </div>
          <div class="block two-thirds"><%= image_tag 'itinerary/day-2-2016.jpg' %></div>
        </div>
    </div>

    <div class="itinerary__row">
        <div class="itinerary__inner-row">
          <div class="block one-third">
            <h1>Day 3</h1>
            <h2>Agile Leadership</h2>
            <p>This day is about being mentally and physically agile to help you succeed, going beyond your perceived limitations and working with the support of your team.</p>
            <p>Applying your leadership, you will work with each other and with coaches to help prepare you for the final challenge.</p>
          </div>
          <div class="block two-thirds"><%= image_tag 'itinerary/day-3-2016.jpg' %></div>
        </div>
    </div>

    <div class="itinerary__row">
        <div class="itinerary__inner-row">
          <div class="block one-third">
            <h1>Day 4</h1>
            <h2>Execution Challenge</h2>
            <p>Putting it all together, your team will run your business and earn real money as you deal with real customers!</p>
            <p>Through friendly competition, earn the  honour of being the most profitable business among your peers</p>
          </div>
          <div class="block two-thirds"><%= image_tag 'itinerary/day-4-2016.jpg' %></div>
        </div>
    </div>
</div>

app/views/pages/reminders.erb
<%= render partial: "shared/nav" %>
<div class="reminders__container">
  <h1 class="reminders__header">Reminders</h1>
  <h2>Foreign Participants</h2>
  <ul>
    <li>Affidavit of consent from the parents (approved by the embassy)</li>
  </ul>
  <br />
  <br />
  <%= image_tag 'coming-soon.jpg', class: "coming-soon-img" %>
</div>

app/views/pages/thank_you.erb
<%= render partial: "shared/nav" %>
<div class="contact__container">
  <h1 class="registration__header">Register</h1>

  <div class="block__container">
    <div class="block one-half">
      <%= render partial: "shared/reg/thankyou" %>
    </div>

    <div class="block one-half">
      <%= image_tag "register-image.jpg", class: "register__image" %>
    </div>
  </div>

</div>

app/views/shared/_faq_content.erb
<div class="block__container faq__content">
  <div class="block">
    <p class="question">What is this program about? Why should I send my child for this and not any other available program?</p>
    <p>This program is specially designed for EO, and is not available to the public. Many of the activities involve EO Members as mentors and case studies.</p>

    <p class="question">What kind of activities? What will the children be doing?</p>
    <p>Much of the program consists of experiential learning, with minimal lectures. The program has a lot of learning and competitive games, so that the children learn in an exciting and fun way.</p>

    <p>They have an opportunity to set up their own business and compete against each other, as if in the real world.</p>

    <p class="question">How would it benefit them?</p>
    <p>This program does not only benefit the children but also the parents.</p>

    <%= image_tag "faq/workshop.png", class: "lb-image" %>
  </div>
</div>

app/views/shared/_nav.erb
<nav class="main-nav">
  <a href="/" class="logo">MyEO Next Gen Manila</a>
  <ul>
    <li id="aboutL"><a href="/">Home</a></li>
    <li id="itineraryL"><a href="itinerary.html">Itinerary</a></li>
    <li id="remindersL"><a href="reminders.html">Reminders</a></li>
    <li id="faqL"><a href="faq.html">FAQs</a></li>
    <li id="contactL"><a href="contact.html">Register</a></li>
    <li class="underline"></li>
  </ul>
</nav>

app/views/shared/faq/_attendees.erb
<div class="block__container faq__content">
  <div class="block">
    <p class="question">ATTENDEES</p>
    <p>MyEO Next Gen Manila 2016 is open to teens of EO members and sponsored relatives/friends, 13-18 years old. Participants will be grouped by age bracket and there will be many opportunities throughout the program for them to interact with other groups.</p>

    <%= image_tag "faq/attendees.png", class: "lb-image" %>
  </div>
</div>

app/views/shared/faq/_bring.erb
<div class="block__container faq__content">
    <div class="block">
        <p class="question">WHAT TO BRING</p>
        <p>The following is a list of items to needed for the BootCamp.</p>
        <ul class="item-list">
            <li class="item">4 sets of clothes for daytime activities</li>
            <li class="item">2 sets of clothes for physical activities Running shoes or sneakers</li>
            <li class="item">Cap, hat or visor</li>
            <li class="item">Swimming attire and fit-flops</li>
            <li class="item">Light rain jacket</li>
            <li class="item">Sunblock and insect repellant</li>
            <li class="item">Personal medication, vitamins</li>
            <li class="item">Eyeglasses, contact lenses and cleaning solution (if needed) Refillable water bottle</li>
            <li class="item">Mobile phone with charging cable</li>
            <li class="item">Small laptop or tablet (for web research and/or presentations; having Microsoft Office/Apple iWork installed is recommended)</li>
            <li class="item">Props, costumes, musical instruments, etc to help showcase Camper’s unique skills on talent night (optional)</li>
            <li class="item">Pocket money (Php 2,000) for souvenirs, personal snacks, etc.</li>
        </ul>
    </div>
</div>

app/views/shared/faq/_drop_off.erb
<div class="block__container faq__content">
    <div class="block">
        <p class="question">DROP OFF + PICK UP</p>
        <p>Registration on Thursday 31 March begins at 7:30am at the Glass House, Mezzanine Floor of the New World Hotel. Parking is available at the hotel or at the Greenbelt Malls fronting the venue. Please come early to give time to register and check-in luggage. By 8:30 parents, will say goodbye to their teens and leave them in our capable hands.</p>
        <p>The next time you will see them will be at our open house at the Legaspi Village Sunday Market on 3 April from 7:00am to 12:00nn. Family and friends are welcome to witness the Campers in action. Participants will be presenting their projects starting 9:00am. The Legaspi Village Sunday Market is located in the Legaspi Open Parking, Legaspi cor. VA Rufino Streets, Legaspi Village Makati.</p>
        <p>Street parking is available and do come early as slots tend to fill up quickly.</p>
        <p>Finally, parents are welcome to join us for coffee at 3:00pm at the Ballroom Foyer back at the New World Hotel and celebrate the Awarding and Closing Ceremony at 3:30pm in the New World Ballroom. Next Gen Manila 2016 officially ends at 4:30pm.</p>
    </div>
</div>

app/views/shared/faq/_happen.erb
<div class="block__container faq__content">
    <div class="block">
        <p class="question">WHAT’S GOING TO HAPPEN</p>
        <p>Our Next Gen Campers will have many things in store for them in the next 4 days. Our objectives our simple - develop entrepreneurial skills, provide networking opportunities, and have a fun time doing both.</p>
        <p>In participating in the BootCamp, your teens will gain knowledge, skills and mindsets needed to be successful entrepreneurs. We will achieve this through interactive workshop sessions, special guest speakers and coaching opportunities with people already in the business. Each day will have a specific theme and sessions that progressively grow, building up on each other. They will then apply this knowledge in the mini-challenges throughout the 4 days, leading up to the Final Business Challenge that awaits them on our last day. Mission and vision, strategic thinking, branding, communication, results focus and leadership are only some of the key insights our attendees will take back with them after Next Gen.</p>
        <p>Aside from opening their minds to new information we also want to open our participant’s souls - to creating lasting bonds among our future entrepreneurs. Throughout the day, participants will get together and work on given tasks, helping them learn a bit more about each other every time. And every evening, we will have less formal activities to give the entire team an opportunity to relax, make new friends and hangout.</p>
        <p>Our job is to make your teens feel they’ve gotten the most value from their 4 days at Next Gen Manila.</p>

        <%= image_tag "faq/workshop.png", class: "lb-image" %>
    </div>
</div>

app/views/shared/faq/_safety.erb
<div class="block__container faq__content">
  <div class="block">
    <p class="question">Safety + Security</p>
    <p>The safety of our attendees is our top priority. We will be having an onsite emergency medical technician (EMT) staying with us in the Hotel for the entire duration of the BootCamp. Our EMT will work in coordination with the New World Hotel clinic and emergency services in the Legaspi Village community and Makati Medical Centre, so should we require any assistance, we’ve got it covered. Additionally, we are employing a security team to help our program Marshals watch over our participants particularly when we step out of the venue for activities or dining out.</p>
    <p>If you haven’t yet filled out or submitted the registration forms and medical questionnaire, please do so prior to the start of the program. We will have copies available during registration on the 31 March just in case.</p>

        <%= image_tag "faq/security.png", class: "lb-image" %>
  </div>
</div>

app/views/shared/faq/_transport.erb
<div class="block__container faq__content">
  <div class="block">
    <p class="question">TRANSPORT + ACCOMODATIONS</p>
    <p>Transportation to and from the BootCamp will be on the attendees expense. Participants will have comfortable triple-sharing accommodations at the New World Hotel. All meals for the duration of the program will be covered by us. And on occasion we step out of the hotel for activities, whether on foot or in vans, we will provide the necessary transportation, supervision and security.</p>

    <%= image_tag "faq/trans-and-acc.png", class: "lb-image" %>
  </div>
</div>

app/views/shared/faq/_wwww.erb
<div class="block__container faq__content">
  <div class="block">
    <p class="question">WHO WHAT WHEN WHERE</p>
    <p>MyEO Next Gen Manila 2016 is a 4-day Entrepreneurs Bootcamp open to teens of EO members from ages 13-18.</p>
    <p>It is an exciting program where participants learn and apply essential business management, communication and leadership skills as they collaborate with each other and with industry professionals and EO guest coaches.</p>
    <p>Next Gen will be held at the New World Hotel in Makati, Philippines from 31 March to 3 April 2016.</p>
  </div>
</div>

app/views/shared/reg/_kidReg.erb
<form class="registration__form" id="KidRegistration">

    <label for="lname">Last Name:</label><input id="lname" type="text"/>
    <label for="fname">First Name:</label><input id="fname" type="text"/>
    <label for="nname">Nickname:</label><input id="nname" type="text"/>
    <label for="nname">Birthdate:</label><input id="nname" type="text"/>
    <label for="email">E-mail Address:</label><input id="email" type="email"/>

    <div class="registration__form--checkbox">
        <div class="checkbox__inner">
            <h3>Hobbies and interests, check one:</h3>
            <div class="cb__container">
                <label for="cbTV">TV</label>
                <input id="cbTV" type="radio" value="TV" name="hobbies" />
            </div>

            <div class="cb__container">
                <label for="cbFilm">Film</label>
                <input id="cbFilm" type="radio" value="Film" name="hobbies" />
            </div>

            <div class="cb__container">
                <label for="cbVideoGames">Video Games</label>
                <input id="cbVideoGames" type="radio" value="Video Games" name="hobbies" />
            </div>

            <div class="cb__container">
                <label for="cbMusic">Music</label>
                <input id="cbMusic" type="radio" value="Music" name="hobbies" />
            </div>

            <div class="cb__container">
                <label for="cbSports">Sports</label>
                <input id="cbSports" type="radio" value="Sports" name="hobbies" />
            </div>

            <div class="cb__container">
                <label for="cbFashion">Fashion</label>
                <input id="cbFashion" type="radio" value="Fashion" name="hobbies" />
            </div>

            <div class="cb__container">
                <label for="cbFood">Food</label>
                <input id="cbFood" type="radio" value="Food" name="hobbies" />
            </div>

            <div class="cb__container">
                <label for="cbTechnology">Technology</label>
                <input id="cbTechnology" type="radio" value="Technology" name="hobbies" />
            </div>

            <div class="cb__container">
                <label for="cbScience">Science</label>
                <input id="cbScience" type="radio" value="Science" name="hobbies" />
            </div>

            <div class="cb__container">
                <label for="cbOther">Other</label>
                <input id="cbOther" type="radio" value="Other" name="hobbies" />
            </div>
        </div>
    </div>

    <div class="registration__form--checkbox">
        <div class="checkbox__inner">
            <h3> Shirt Size:</h3>
            <div class="cb__container">
                <label for="cbXS">XS (17.5" at the chest, 24" length)</label>
                <input id="cbXS" type="radio" name="shirtSizes" value="XS" />
            </div>

            <div class="cb__container">
                <label for="cbS">S (18.5" at the chest, 25" length)</label>
                <input id="cbS" type="radio" name="shirtSizes" value="S" />
            </div>

            <div class="cb__container">
                <label for="cbM">M (19.5" at the chest, 26" length)</label>
                <input id="cbM" type="radio" name="shirtSizes" value="M" />
            </div>

            <div class="cb__container">
                <label for="cbL">L (20.5" at the chest, 27" length)</label>
                <input id="cbL" type="radio" name="shirtSizes" value="L" />
            </div>

            <div class="cb__container">
                <label for="cbXL">XL (21.5" at the chest, 27.5" length)</label>
                <input id="cbXL" type="radio" name="shirtSizes" value="XL" />
            </div>

            <div class="cb__container">
                <label for="cbXXL">XXL (23" at the chest, 28" length)</label>
                <input id="cbXXL" type="radio" name="shirtSizes" value="XXL" />
            </div>

            <div class="cb__container">
                <label for="cbXXXL">XXXL (28.5" at the chest, 28.5" length)</label>
                <input id="cbXXXL" type="radio" name="shirtSizes" value="XXXL" />
            </div>
        </div>
    </div>

    <label for="medCondition">Any medical condition we should be aware of?</label><textarea id="medCondition"></textarea>
    <label for="dietary">Any special dietary requirements we should know about??</label><textarea id="dietary"></textarea>

    <div class="button__container">
        <button type="submit" class="registration__form--button"><span>Submit</span></button>
        <button type="submit" class="registration__form--button"><span data-target="reset">Fill out Next Form</span></button>
    </div>
</form>

app/views/shared/reg/_member_form.erb
<%= form_for member, url: do_register_path, html: { class: "registration__form isActive" } do |f| %>
  <p class="registration__form-message">
    <span>Reminder:</span><br />
    Event is only open to children and relatives of EO, YPO, and EO Accelerator members.
  </p>

  <% unless f.object.errors.full_messages_for(:last_name).blank? %>
    <p class="error"><%= f.object.errors.full_messages_for(:last_name).join(", ") %></p>
  <% end %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <% unless f.object.errors.full_messages_for(:first_name).blank? %>
    <p class="error"><%= f.object.errors.full_messages_for(:first_name).join(", ") %></p>
  <% end %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <% unless f.object.errors.full_messages_for(:member_number).blank? %>
    <p class="error"><%= f.object.errors.full_messages_for(:member_number).join(", ") %></p>
  <% end %>
  <%= f.label :member_number %>
  <%= f.text_field :member_number %>

  <% unless f.object.errors.full_messages_for(:email).blank? %>
    <p class="error"><%= f.object.errors.full_messages_for(:email).join(", ") %></p>
  <% end %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <% unless f.object.errors.full_messages_for(:contact_number).blank? %>
    <p class="error"><%= f.object.errors.full_messages_for(:contact_number).join(", ") %></p>
  <% end %>
  <%= f.label :contact_number %>
  <%= f.text_field :contact_number %>

  <div class="input-group">
    <% unless f.object.errors.full_messages_for(:payment_option).blank? %>
      <p class="error"><%= f.object.errors.full_messages_for(:payment_option).join(", ") %></p>
    <% end %>
    <%= f.label :payment_option %>
    <%= f.select :payment_option, ["Bank Deposit", "Cash"] %>
  </div>

  <div class="input-group">
    <!-- checkbox -->
    <div class="terms">
      <% unless f.object.errors.full_messages_for(:i_agree).blank? %>
        <p class="error"><%= f.object.errors.full_messages_for(:i_agree).join(", ") %></p>
      <% end %>
      <label><%= f.check_box :i_agree %> I agree to the terms specified in the <span class="waiver-toggle js-toggle-waiver">waiver and permission</span> form.</label>
      <div id="waiver" class="waiver">
        <h3>Waiver and Permission</h3>
        <p>This waiver and permission form serves as notice that I am allowing my teen/s to join the MyEO NextGen Bootcamp 2.0. In the event that he/she becomes ill or sustains injury or if any untoward accident happens while participating, I, as legal parent or guardian, understand that every effort will be made to contact me. In the event that I cannot be reached, I hereby give my permission to the physician selected to rescue, provide proper treatment. </p>
        <p>I also release EO Philippines, Management Strategies Inc, and all staff and volunteers involved in the MyEO NextGen Bootcamp from any liability in such situations. </p>
        <p>I hereby assume all of the risks of participating in the MyEO NextGen Bootcamp 2. I certify that my child is physically fit and have not been advised to not participate by a qualified medical professional. I certify that there are no health-related reasons or problems which hinder my child’s participation in the activities. </p>
      </div>
    </div>
  </div>

  <div class="participants" %>
    <%= f.fields_for :participants do |pf| %>
      <%= render "shared/reg/participant_form", f: pf %>
    <% end %>
  </div>

  <div class="button__container">
    <button type="submit" class="registration__form--button"><span>Submit</span></button>
    <button class="registration__form--button js-add-participant"><span>Add Another Child</span></button>
  </div>
<% end %>

<%= form_for Member.new, url: "#" do |f| %>
  <div class="js-participant-field hidden">
    <%= f.fields_for :participants, Participant.new do |pf| %>
      <%= render "shared/reg/participant_form", f: pf %>
    <% end %>
  </div>
<% end %>

app/views/shared/reg/_payment.erb
<form class="registration__form isActive" id="PaymentForm">
    <p class="registration__form-message">
      <span>Reminder:</span><br />
      Event is only open to children and relatives of EO, YPO, and EO Accelerator members.
    </p>
    <label for="lname">Last Name:</label><input id="lname" type="text"/>
    <label for="fname">First Name:</label><input id="fname" type="text"/>
    <label for="member">Referred By:</label><input id="member" type="text"/>
    <label for="email">E-mail Address:</label><input id="email" type="email"/>
    <label for="contact">Contact Number:</label><input id="contact" type="text"/>

    <div class="input-group">
      <label for="kids">How many kids are you signing up for?</label><input id="kids" type="number" />
    </div>

    <div class="input-group">
      <label for="payment">Choose payment option</label>
      <select id="payment">
        <option>Bank Deposit</option>
        <option>Cash</option>
      </select>
    </div>

    <div class="button__container">
      <button type="submit" class="registration__form--button"><span data-target="#ThankYouMsg">Next</span></button>
    </div>
</form>

app/views/shared/reg/_thankyou.erb
<div class="registration__form thankyou isActive" id="ThankYouMsg">
    <p class="registration__form-message">
        Thanks for participating! We’re sure your teens will have an amazing experience!
    </p>

    <p class="registration__form-message">
        Please check your e-mail for further instructions on how you can finalise the payment process.
    </p>

    <p class="registration__form-message">
        We will also be e-mailing you in the weeks before the event for final reminders and other updates.
    </p>

    <!-- <p class="registration__form-message">
        For now, click next to fill out the <br /><span>CAMPERS’ INFORMATION SHEET</span>
    </p>

    <div class="button__container">
        <button type="submit" class="registration__form--button"><span data-target="#KidRegistration">Next</span></button>
    </div> -->
</div>